# Generated by Django 5.1.4 on 2024-12-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='Options for dropdown/checkbox questions.', null=True),
        ),
    ]
